export enum OnboardingStatus {
    REGISTERED = "REGISTERED",
    PROFILE_CREATED = "PROFILE_CREATED",
    TEAM_PENDING = "TEAM_PENDING",
    COACH_PENDING_APPROVAL = "COACH_PENDING_APPROVAL",
    ACTIVE = "ACTIVE"
}