
services:
  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: intellifutsal_react_frontend_standalone
    restart: always
    ports:
      - "3000:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
    name: intellifutsal-frontend-network